{% set version = "1.12.2" %}

package:
  name: cffi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cffi/cffi-{{ version }}.tar.gz
  sha256: e113878a446c6228669144ae8a56e268c91b7f1fafae927adc4879d9849e0ea7
  patches:
    - setup-linux.patch  # [not win]

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libffi  # [not win]
    - pycparser
  run:
    - python
    - libffi  # [not win]
    - pycparser

test:
  imports:
    - cffi
    - _cffi_backend

about:
  home: https://bitbucket.org/cffi/cffi
  license: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
  doc_url: http://cffi.readthedocs.org

extra:
  recipe-maintainers:
    - goanpeca
    - inducer
    - jschueller
    - ocefpaf
