{% set name = "cffi" %}
{% set version = "1.10.0" %}
{% set hash_type = "sha256" %}
{% set hash = "b3b02911eb1f6ada203b0763ba924234629b51586f72a21faacc638269f4ced5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}
  patches:
    - setup-linux.patch  # [unix]
    - 0001-Link-to-dl-library.patch

build:
  number: 0
  script: ${PYTHON} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - libffi  # [unix]
    - pycparser
    - setuptools
  build:
    - {{ compiler('c') }}
  run:
    - python
    - libffi  # [unix]
    - pycparser

test:
  imports:
    - cffi
    - _cffi_backend

about:
  home: https://bitbucket.org/cffi/cffi
  license: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
  doc_url: http://cffi.readthedocs.org

extra:
  recipe-maintainers:
    - goanpeca
    - inducer
    - jschueller
    - mingwandroid
