{% set version = "1.12.0" %}

package:
  name: cffi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cffi/cffi-{{ version }}.tar.gz
  sha256: 08090454ff236239e583a9119d0502a6b9817594c0a3714dd1d8593f2350ba11
  patches:
    - setup-linux.patch  # [not win]

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libffi  # [not win]
    - pycparser
  run:
    - python
    - libffi  # [not win]
    - pycparser

test:
  imports:
    - cffi
    - _cffi_backend

about:
  home: https://bitbucket.org/cffi/cffi
  license: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.
  doc_url: http://cffi.readthedocs.org

extra:
  recipe-maintainers:
    - goanpeca
    - inducer
    - jschueller
    - ocefpaf
