travis:
  secure:
    BINSTAR_TOKEN: g3ehQ63RVHN/SLqv3jqJR2eSffkeziULIsEGPpB3ccYe4WqhoZafB6fr7dBwOI4YwnpPqJPgcLhlJqelBZBLUcC2OSaC8QInd2YdISKkcqou0B2G6b1Ph2hs/Pcuf8a0XdHmxRauNiT/f4WZZK0RCggtNFN31YkIsxZ7I9FR8AuFECesRqAd30Wy8sb9EhZ9pYVG1WuZkHjKZLuR67G0OYH0A7I4uPXOgJJVAIPxT8OPMIkQF/bM17NmJ2oFvtmZq9RJpz7IcGf/l1CiBMwmXH+tbpPp6Xvbar9KVBnSBVA3xgbT6amF84Rs6IzsFC2KfeH6Ce0fbHuaWSKje6rXjkByg6nf3dfV3+/NZQOtgz7qqKECFtnpUGYgETH70++f5o0pXIKA0UXnRb+FiY4OtdV02vzS7oxRkifvlfkq+AJrEHJzDl7BzHvq+XQ4w6bDNulpCmKsB/FaVniYA2ZWsfxv1TFqhhCEwwxmi58ZGzz+Ld6DXucAK6gWaC3Je40BOQoynO9I45Q/36s9qr83zXRi0ffHG6w0Be+Msqbzx8o6TV9oJFhWhokxwGFdX4DYAdlQAfCpu5ljBWHhwQ0x7UQ2ejWORM6Lp3W9Y39sZP5CEpukyV0CBBvrWO+Cjh5vevmvVIv61S3F2GEP8fe5KIVrn4Uc63Bxx+xsbZvascg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
